# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:/HYBIRD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:/HYBIRD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:/HYBIRD/CMakeFiles E:/HYBIRD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:/HYBIRD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hybird

# Build rule for target.
hybird: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hybird
.PHONY : hybird

# fast build rule for target.
hybird/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/build
.PHONY : hybird/fast

src/DEM.obj: src/DEM.cpp.obj
.PHONY : src/DEM.obj

# target to build an object file
src/DEM.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/DEM.cpp.obj
.PHONY : src/DEM.cpp.obj

src/DEM.i: src/DEM.cpp.i
.PHONY : src/DEM.i

# target to preprocess a source file
src/DEM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/DEM.cpp.i
.PHONY : src/DEM.cpp.i

src/DEM.s: src/DEM.cpp.s
.PHONY : src/DEM.s

# target to generate assembly for a file
src/DEM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/DEM.cpp.s
.PHONY : src/DEM.cpp.s

src/IO.obj: src/IO.cpp.obj
.PHONY : src/IO.obj

# target to build an object file
src/IO.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/IO.cpp.obj
.PHONY : src/IO.cpp.obj

src/IO.i: src/IO.cpp.i
.PHONY : src/IO.i

# target to preprocess a source file
src/IO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/IO.cpp.i
.PHONY : src/IO.cpp.i

src/IO.s: src/IO.cpp.s
.PHONY : src/IO.s

# target to generate assembly for a file
src/IO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/IO.cpp.s
.PHONY : src/IO.cpp.s

src/LB.obj: src/LB.cpp.obj
.PHONY : src/LB.obj

# target to build an object file
src/LB.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/LB.cpp.obj
.PHONY : src/LB.cpp.obj

src/LB.i: src/LB.cpp.i
.PHONY : src/LB.i

# target to preprocess a source file
src/LB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/LB.cpp.i
.PHONY : src/LB.cpp.i

src/LB.s: src/LB.cpp.s
.PHONY : src/LB.s

# target to generate assembly for a file
src/LB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/LB.cpp.s
.PHONY : src/LB.cpp.s

src/elmt.obj: src/elmt.cpp.obj
.PHONY : src/elmt.obj

# target to build an object file
src/elmt.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/elmt.cpp.obj
.PHONY : src/elmt.cpp.obj

src/elmt.i: src/elmt.cpp.i
.PHONY : src/elmt.i

# target to preprocess a source file
src/elmt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/elmt.cpp.i
.PHONY : src/elmt.cpp.i

src/elmt.s: src/elmt.cpp.s
.PHONY : src/elmt.s

# target to generate assembly for a file
src/elmt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/elmt.cpp.s
.PHONY : src/elmt.cpp.s

src/hybird.obj: src/hybird.cpp.obj
.PHONY : src/hybird.obj

# target to build an object file
src/hybird.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/hybird.cpp.obj
.PHONY : src/hybird.cpp.obj

src/hybird.i: src/hybird.cpp.i
.PHONY : src/hybird.i

# target to preprocess a source file
src/hybird.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/hybird.cpp.i
.PHONY : src/hybird.cpp.i

src/hybird.s: src/hybird.cpp.s
.PHONY : src/hybird.s

# target to generate assembly for a file
src/hybird.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/hybird.cpp.s
.PHONY : src/hybird.cpp.s

src/node.obj: src/node.cpp.obj
.PHONY : src/node.obj

# target to build an object file
src/node.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/node.cpp.obj
.PHONY : src/node.cpp.obj

src/node.i: src/node.cpp.i
.PHONY : src/node.i

# target to preprocess a source file
src/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/node.cpp.i
.PHONY : src/node.cpp.i

src/node.s: src/node.cpp.s
.PHONY : src/node.s

# target to generate assembly for a file
src/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/node.cpp.s
.PHONY : src/node.cpp.s

src/utils.obj: src/utils.cpp.obj
.PHONY : src/utils.obj

# target to build an object file
src/utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/utils.cpp.obj
.PHONY : src/utils.cpp.obj

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hybird.dir/build.make CMakeFiles/hybird.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hybird"
	@echo "... src/DEM.obj"
	@echo "... src/DEM.i"
	@echo "... src/DEM.s"
	@echo "... src/IO.obj"
	@echo "... src/IO.i"
	@echo "... src/IO.s"
	@echo "... src/LB.obj"
	@echo "... src/LB.i"
	@echo "... src/LB.s"
	@echo "... src/elmt.obj"
	@echo "... src/elmt.i"
	@echo "... src/elmt.s"
	@echo "... src/hybird.obj"
	@echo "... src/hybird.i"
	@echo "... src/hybird.s"
	@echo "... src/node.obj"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/utils.obj"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

